import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import { Toaster } from "sonner";

import { NextAuthProvider } from "@/app/nextAuthProvider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter', });
const poppins = Poppins({ subsets: ["latin"], variable: '--font-poppins', weight: ['400', '600', '700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body className={`${inter.variable} ${poppins.variable}`}>
          <Toaster />
          {children}
        </body>
      </html>
    </NextAuthProvider>
  );
}
